import type { Metadata } from "next";
import "./globals.css";
import { dmSans, roboto } from "./fonts";
import { RootLayoutProps } from "@/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${dmSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
